In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np

In [68]:
from sklearn.datasets import load_digits
digits = load_digits()

In [69]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size=0.3)

In [70]:
svm_model = SVC()
svm_model.fit(X_train, y_train)
svm_model.score(X_test, y_test)

0.9833333333333333

In [71]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
rf_model.score(X_test, y_test)

0.9666666666666667

In [72]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [73]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [74]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [75]:
get_score(LogisticRegression(solver='liblinear'), X_train, X_test, y_train, y_test)

0.9537037037037037

In [76]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9833333333333333

In [77]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9629629629629629

In [78]:
scores_lr = []
scores_svm = []
scores_rf = []
scores_dt = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(solver='liblinear'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
    scores_dt.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))

In [79]:
scores_lr

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [80]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [81]:
scores_rf

[0.9365609348914858, 0.9632721202003339, 0.9248747913188647]

In [82]:
scores_dt

[0.7445742904841403, 0.8163606010016694, 0.7946577629382304]

In [83]:
from sklearn.model_selection import cross_val_score

In [86]:
cross_val_score(LogisticRegression(solver='liblinear'), digits.data, digits.target, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [87]:
cross_val_score(SVC(), digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [88]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=3)

array([0.94156928, 0.95993322, 0.92821369])

In [89]:
cross_val_score(DecisionTreeClassifier(), digits.data, digits.target, cv=3)

array([0.75292154, 0.84307179, 0.76627713])